"use strict";
// Generated from data/projects.json; edit the JSON source and regenerate this file.
window.PORTFOLIO_DATA = {
  "schema": "systems-workflow-portfolio-projects/v1",
  "boundary": "INDEPENDENT PORTFOLIO DEMOS · SYNTHETIC WORKFLOWS · ATTRIBUTED PUBLIC PRODUCT IDENTITY · NO AFFILIATION · NO PRODUCTION ACTION",
  "evidence_note": "Counts describe this rewritten candidate; exact exported-tree evidence is produced by release verification.",
  "projects": [
    {
      "id": "api-integration-contracts",
      "title": "API Integration Contracts",
      "category": "integration",
      "problem": "Make adverse request, response, and webhook behavior reviewable before any action boundary.",
      "evidence": "Strict fixtures, virtual 429 recovery, HMAC/replay/idempotency ordering, quarantine, a human gate, and a deterministic receipt.",
      "route": "projects/api-integration-contracts/index.html",
      "readme": "projects/api-integration-contracts/README.md",
      "hero": "assets/project-previews/api-integration-contracts.png",
      "runtime": "Static browser + Python standard library",
      "unit_tests": 48,
      "browser_checks": 12,
      "non_claim": "No live API, credential, authentication system, or production deployment."
    },
    {
      "id": "public-product-validation",
      "title": "Public Product Validation",
      "category": "catalog",
      "problem": "Parse adverse operator text and corroborate product identity without treating public data as price or approval authority.",
      "evidence": "Barcode normalization, check digits, retained Open Food Facts text records, conflict routing, synthetic prices, and a human decision receipt.",
      "route": "projects/public-product-validation/index.html",
      "readme": "projects/public-product-validation/README.md",
      "hero": "assets/project-previews/public-product-validation.png",
      "runtime": "Static browser",
      "unit_tests": 19,
      "browser_checks": 12,
      "non_claim": "Public identity evidence is not authoritative; prices are synthetic; no product images or live writes."
    },
    {
      "id": "human-in-the-loop-control",
      "title": "Human-in-the-Loop Control",
      "category": "operations",
      "problem": "Resolve known identifiers, hold unknowns, reread staged changes, and keep the final save behind a person.",
      "evidence": "A pure executable core, native Tk lab, code-native browser preview, mismatch stop, explicit approval, and temporary-path logging.",
      "route": "projects/human-in-the-loop-control/preview/index.html",
      "readme": "projects/human-in-the-loop-control/README.md",
      "hero": null,
      "runtime": "Static browser + Python standard library/Tk",
      "unit_tests": 15,
      "browser_checks": 15,
      "non_claim": "Invented records and in-memory state only; no account, service, persistence, or production authority."
    },
    {
      "id": "ai-evaluation-release-gates",
      "title": "AI Evaluation Release Gates",
      "category": "governance",
      "problem": "Separate exact checks, blind judgment, holdout evidence, and release authority.",
      "evidence": "Precomputed synthetic A/B cases, exact graders, local holdout reveal, hard vetoes, and fail-closed outcomes.",
      "route": "projects/ai-evaluation-release-gates/index.html",
      "readme": "projects/ai-evaluation-release-gates/README.md",
      "hero": "assets/project-previews/ai-evaluation-release-gates.png",
      "runtime": "Static browser + Python standard library",
      "unit_tests": 60,
      "browser_checks": 19,
      "non_claim": "No inference, real provider evaluation, confidential holdout, or deployment authority."
    },
    {
      "id": "implementation-readiness",
      "title": "Implementation Readiness",
      "category": "operations",
      "problem": "Make evidence gaps, owners, actions, and acceptance prerequisites inspectable before launch work advances.",
      "evidence": "Six offline views, explicit gap/action states, evidence locators, a separate reviewer acknowledgment, and an audit export.",
      "route": "projects/implementation-readiness/index.html",
      "readme": "projects/implementation-readiness/README.md",
      "hero": "assets/project-previews/implementation-readiness.png",
      "runtime": "Static browser",
      "unit_tests": 13,
      "browser_checks": 10,
      "non_claim": "No vendor behavior, assessment, certification, customer record, or production action."
    },
    {
      "id": "customer-launch-readiness",
      "title": "Customer Launch Readiness",
      "category": "operations",
      "problem": "Keep discovery decisions, launch blockers, evidence, handoffs, and acceptance from collapsing into one status.",
      "evidence": "Six offline views, staged readiness transitions, exception reproduction, named handoffs, explicit acceptance, and an audit export.",
      "route": "projects/customer-launch-readiness/index.html",
      "readme": "projects/customer-launch-readiness/README.md",
      "hero": "assets/project-previews/customer-launch-readiness.png",
      "runtime": "Static browser",
      "unit_tests": 14,
      "browser_checks": 11,
      "non_claim": "No vendor software, customer data, authorized go-live, deployment, or production action."
    },
    {
      "id": "support-triage-workbench",
      "title": "Support Triage Workbench",
      "category": "operations",
      "problem": "Route incomplete support intake without guessing facts or sending an unreviewed response.",
      "evidence": "Strict schemas, deterministic triage, ambiguity and safety holds, redaction, human approval, and a hash-linked local audit.",
      "route": "projects/support-triage-workbench/README.md",
      "readme": "projects/support-triage-workbench/README.md",
      "hero": null,
      "runtime": "Python standard library CLI",
      "unit_tests": 21,
      "browser_checks": 0,
      "non_claim": "No ticketing account, message send, customer workflow, or external persistence."
    },
    {
      "id": "catalog-migration-validator",
      "title": "Catalog Migration Validator",
      "category": "catalog",
      "problem": "Reconcile a schema migration without hiding malformed or unmapped records.",
      "evidence": "Strict mappings, quarantine, count reconciliation, content-addressed planning, exact confirmation, and verified local apply.",
      "route": "projects/catalog-migration-validator/README.md",
      "readme": "projects/catalog-migration-validator/README.md",
      "hero": null,
      "runtime": "Python standard library CLI",
      "unit_tests": 40,
      "browser_checks": 0,
      "non_claim": "No live hospitality adapter, remote transaction, or production migration."
    },
    {
      "id": "claim-evidence-linter",
      "title": "Claim–Evidence Linter",
      "category": "governance",
      "problem": "Check whether each declared claim satisfies its explicit evidence policy.",
      "evidence": "Typed assertions, exact citation spans, deterministic verdicts, fail-closed parsing, and rebuild verification.",
      "route": "projects/claim-evidence-linter/README.md",
      "readme": "projects/claim-evidence-linter/README.md",
      "hero": null,
      "runtime": "Python standard library CLI",
      "unit_tests": 52,
      "browser_checks": 0,
      "non_claim": "Does not establish source truth, independence, or semantic entailment."
    },
    {
      "id": "interface-contract-harness",
      "title": "Interface Contract Harness",
      "category": "quality",
      "problem": "Catch bounded, deterministic accessibility-oriented HTML contract drift.",
      "evidence": "Nine documented static rules, exact expected fingerprints, reproducible reports, and a SHA-256 evidence chain.",
      "route": "projects/interface-contract-harness/demo/index.html",
      "readme": "projects/interface-contract-harness/README.md",
      "hero": "assets/project-previews/interface-contract-harness.png",
      "runtime": "Python standard library CLI + static report",
      "unit_tests": 41,
      "browser_checks": 0,
      "non_claim": "Not WCAG conformance, browser behavior, legal certification, or assistive-technology testing."
    },
    {
      "id": "catalog-lifecycle",
      "title": "Catalog Lifecycle",
      "category": "catalog",
      "problem": "Make verified, review, held, and unknown catalog states legible to an operator.",
      "evidence": "A four-screen static workflow with record diffs, explicit unknown holds, local review state, and an audit presentation.",
      "route": "projects/catalog-lifecycle/index.html",
      "readme": "projects/catalog-lifecycle/README.md",
      "hero": "assets/project-previews/catalog-lifecycle.png",
      "runtime": "Static browser",
      "unit_tests": 12,
      "browser_checks": 0,
      "non_claim": "Interface simulation only; no integration, persistence, or production automation."
    },
    {
      "id": "bulk-price-control",
      "title": "Bulk Price Control",
      "category": "catalog",
      "problem": "Apply a reviewed price batch without collapsing preview, approval, write, and verification.",
      "evidence": "Write-free preview, staged digest, exact human confirmation, atomic local commit, reread verification, and rollback evidence.",
      "route": "projects/bulk-price-control/README.md",
      "readme": "projects/bulk-price-control/README.md",
      "hero": null,
      "runtime": "Python standard library CLI",
      "unit_tests": 43,
      "browser_checks": 0,
      "non_claim": "No point-of-sale, database, cloud connector, or production price change."
    }
  ]
};
