#!/usr/bin/env python3
"""Rebuild deterministic examples in temporary copies and compare exact bytes."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


PROJECTS = {
    "interface-contract-harness": {
        "commands": [
            [sys.executable, "-B", "-m", "wcag_harness", "run", "--manifest", "fixtures/manifest.json", "--out", "build"],
            [sys.executable, "-B", "-m", "wcag_harness", "verify", "--audit", "build/audit.json", "--seal", "build/audit.sha256"],
        ],
        "files": ["build/audit.json", "build/audit.sha256", "build/report.html", "build/report.json", "build/report.md"],
    },
    "api-integration-contracts": {
        "commands": [[sys.executable, "-B", "scripts/build_artifacts.py", "--confirm", "SYNTHETIC_ARTIFACTS"]],
        "files": ["artifacts/synthetic_receipt.json", "data/demo_snapshot.js"],
    },
    "ai-evaluation-release-gates": {
        "commands": [[sys.executable, "-B", "scripts/build_artifacts.py"]],
        "files": ["artifacts/reference_hold_receipt.json", "data/demo_snapshot.js", "data/holdout_snapshot.js"],
    },
    "public-product-validation": {
        "commands": [[sys.executable, "-B", "scripts/build_catalog_snapshot.py"]],
        "files": ["data/catalog_snapshot.js"],
    },
}


def verify_root(root: Path) -> list[str]:
    source = (root / "data" / "projects.json").read_text(encoding="utf-8").rstrip("\n")
    expected = (
        '"use strict";\n'
        "// Generated from data/projects.json; edit the JSON source and regenerate this file.\n"
        f"window.PORTFOLIO_DATA = {source};\n"
    )
    observed = (root / "project-data.js").read_text(encoding="utf-8")
    return [] if observed == expected else ["project-data.js differs from the exact data/projects.json wrapper"]


def verify_project(project: Path) -> list[str]:
    spec = PROJECTS.get(project.name)
    if spec is None:
        return [f"unsupported generated-example project: {project.name}"]
    environment = os.environ.copy()
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    with tempfile.TemporaryDirectory(prefix=f"generated-{project.name}-") as directory:
        temporary = Path(directory) / project.name
        shutil.copytree(project, temporary)
        environment["PYTHONPATH"] = str(temporary)
        for command in spec["commands"]:
            result = subprocess.run(
                command,
                cwd=temporary,
                env=environment,
                text=True,
                capture_output=True,
                check=False,
                timeout=90,
            )
            if result.returncode != 0:
                return [f"generator failed ({' '.join(command)}): {result.stderr or result.stdout}"]
        errors = []
        for raw in spec["files"]:
            expected = project / raw
            observed = temporary / raw
            if not expected.is_file() or not observed.is_file():
                errors.append(f"generated file missing: {raw}")
            elif expected.read_bytes() != observed.read_bytes():
                errors.append(f"generated byte mismatch: {raw}")
        return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--root", type=Path)
    group.add_argument("--project", type=Path)
    args = parser.parse_args()
    if args.root:
        label = "root project data"
        errors = verify_root(args.root.resolve())
    else:
        project = args.project.resolve()
        label = project.name
        errors = verify_project(project)
    if errors:
        for error in errors:
            print(f"FAIL: {error}")
        return 1
    print(f"PASS: {label} regenerated byte-for-byte in an isolated temporary copy")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
